import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "IdeaCreate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-sans h-screen">
      <body className="m-0 flex flex-col h-screen">
        <Header />
        {children}
      </body>
    </html>
  );
}
